// <auto-generated />
using System;
using KSubMaker.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KSubMaker.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KSubMakerDbContext))]
    [Migration("20260802033620_AddJobSourceOverride")]
    partial class AddJobSourceOverride
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("KSubMaker.Domain.Jobs.Job", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectedLanguage")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasAudioTrack")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasEmbeddedSubtitle")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasExternalSubtitle")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasKoreanSubtitle")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LanguageProbability")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("LastWriteTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<double>("OverallProgress")
                        .HasColumnType("REAL");

                    b.Property<double>("ProcessingSpeed")
                        .HasColumnType("REAL");

                    b.Property<int>("QueueOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SelectedAudioTrackIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedSubtitleLanguage")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SelectedSubtitleTrackIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceOverride")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<double>("StageProgress")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslationEngine")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslationModel")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("WhisperModel")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QueueOrder")
                        .HasDatabaseName("IX_Jobs_QueueOrder");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Jobs_Status");

                    b.HasIndex("VideoPath")
                        .HasDatabaseName("IX_Jobs_VideoPath");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("KSubMaker.Domain.Models.ModelInstallation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("DownloadedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Installed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("InstalledAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("RecommendedVramBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Verified")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("VerifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Models_Type");

                    b.ToTable("Models", (string)null);
                });

            modelBuilder.Entity("KSubMaker.Infrastructure.Persistence.SettingRecord", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
